{
 "title": "Python Service - Errors & Latency",
 "tags": [
  "prometheus",
  "python",
  "demo"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total RPS",
   "type": "stat",
   "gridPos": { "x": 0, "y": 0, "w": 6, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[1m]))"
    }
   ]
  },
  {
   "title": "5xx RPS",
   "type": "stat",
   "gridPos": { "x": 6, "y": 0, "w": 6, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{status=~\"5..\"}[1m]))"
    }
   ]
  },
  {
   "title": "Error Rate (%)",
   "type": "stat",
   "gridPos": { "x": 12, "y": 0, "w": 6, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * sum(rate(http_requests_total{status=~\"5..\"}[5m])) / sum(rate(http_requests_total[5m]))"
    }
   ]
  },
  {
   "title": "p95 Latency (ms)",
   "type": "stat",
   "gridPos": { "x": 18, "y": 0, "w": 6, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1000 * histogram_quantile(0.95, sum by (le) (rate(http_request_duration_seconds_bucket[5m])))"
    }
   ]
  },
  {
   "title": "Errors by status (RPS)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 4, "w": 12, "h": 7 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (status) (rate(http_requests_total[1m]))"
    }
   ]
  },
  {
   "title": "p50/p95/p99 latency (ms)",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 4, "w": 12, "h": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "1000 * histogram_quantile(0.50, sum by (le) (rate(http_request_duration_seconds_bucket[5m])))"
    },
    {
     "expr": "1000 * histogram_quantile(0.95, sum by (le) (rate(http_request_duration_seconds_bucket[5m])))"
    },
    {
     "expr": "1000 * histogram_quantile(0.99, sum by (le) (rate(http_request_duration_seconds_bucket[5m])))"
    }
   ]
  },
  {
   "title": "Apdex-ish (<=100ms vs total)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 11, "w": 12, "h": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_bucket{le=\"0.1\"}[5m])) / sum(rate(http_request_duration_seconds_count[5m]))"
    }
   ]
  },
  {
   "title": "In-flight",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 11, "w": 12, "h": 7 },
   "targets": [
    { "expr": "max(http_inflight_requests)" }
   ]
  }
 ]
}